// <auto-generated />
namespace BloodDonationMvcApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class divdistTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(divdistTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051245146_divdistTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
